version: '3.1'

services:
  app:
    container_name: app
    build: ./
    ports:
      - 3333:3333
    environment:
      - MONGODB_URL=mongodb://root:password@mongo:27017/admin
      - PORT=3333
      - JWT_SECRET=leducthang98
      - REDIS_PASSWORD=password 
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - REDIS_URL=redis://default:password@redis:6379
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - './data:/data/db'
  mongo-express:
    image: mongo-express
    container_name: mongo-admin
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/
    depends_on:
      - mongo
  redis:
    image: redis
    container_name: redis
    restart: always
    command: redis-server --requirepass password
    volumes:
      - './data-redis:/data'
    ports:
      - 6379:6379